# Runs the test suite and updates the lambda function code
# Be careful! There are production values hardcoded into this workflow
# like the access keys (secrets from the git repo), the lambda function names
# and the S3 bucket and key

name: Test and Deploy

# Run this on every branch cause I'm only developing on master
on:
  push:

jobs:
  # test:
  #   name: Run test suite

  #   runs-on: ubuntu-latest
  #   container: python:3.7-slim-buster

  #   env:
  #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  #   steps:
  #       - name: Git Checkout
  #         uses: actions/checkout@v2
  #         with:
  #           fetch-depth: 1
  #       - name: Set up virtual env and run tests
  #         run: |
  #           python3 -m venv venv
  #           . venv/bin/activate
  #           pip install -r requirements.txt
  #           pip install -e .
  #           pytest

  deploy:
    name: Deploy Lambda package
    needs:
      - test
    runs-on: ubuntu-latest
    container: python:3.7-slim-buster
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-west-2
        ZIP_FILE_BUCKET: apc-tf
        ZIP_FILE_KEY: lambda_functions_deployment_packages/crypto/function.zip

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install Packages
        run: |
          apt-get update
          apt-get -y install zip
          apt-get -y install awscli
      - name: Deploy Lambda Function Package
        run: |
          # bash deploy.sh
          aws s3 ls
